(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.QuizmonLearningPath = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  function createModules({ TYPES, pathImpactSpec, pathPokemonSpec, pathPokemonImpactSpec, pathExamSpec }) {
    const allTypeModules=["types-elements","types-energy","types-earth","types-mind","types-material","types-myth"];
    return [
      { id:"basics-direction", stage:"basics", number:"01", icon:"→", titleKey:"path.module.direction.title", subtitleKey:"path.module.direction.subtitle", introKey:"path.module.direction.intro", exampleKey:"path.module.direction.example", memoryKey:"path.module.direction.memory", types:["water","fire"], demo:pathImpactSpec("water",["fire"],[.5,1,2]), questions:[pathImpactSpec("water",["fire"]),pathImpactSpec("fire",["water"]),pathImpactSpec("grass",["water"]),pathImpactSpec("electric",["water"]),pathImpactSpec("ground",["electric"])], prerequisites:[] },
      { id:"basics-factors", stage:"basics", number:"02", icon:"×", titleKey:"path.module.factors.title", subtitleKey:"path.module.factors.subtitle", introKey:"path.module.factors.intro", exampleKey:"path.module.factors.example", memoryKey:"path.module.factors.memory", types:["electric","ground"], demo:pathImpactSpec("electric",["ground"],[0,.5,1,2]), questions:[pathImpactSpec("water",["fire"]),pathImpactSpec("fire",["water"]),pathImpactSpec("normal",["water"]),pathImpactSpec("electric",["ground"]),pathImpactSpec("ground",["electric"])], prerequisites:["basics-direction"] },
      { id:"types-elements", stage:"types", number:"03", icon:"◈", titleKey:"path.module.elements.title", subtitleKey:"path.module.elements.subtitle", introKey:"path.module.elements.intro", exampleKey:"path.module.elements.example", memoryKey:"path.module.elements.memory", types:["fire","water","grass"], demo:pathImpactSpec("water",["fire"],[.5,1,2]), questions:[pathImpactSpec("fire",["grass"]),pathImpactSpec("water",["fire"]),pathImpactSpec("grass",["water"]),pathImpactSpec("fire",["water"]),pathImpactSpec("grass",["fire"])], prerequisites:["basics-factors"] },
      { id:"types-energy", stage:"types", number:"04", icon:"ϟ", titleKey:"path.module.energy.title", subtitleKey:"path.module.energy.subtitle", introKey:"path.module.energy.intro", exampleKey:"path.module.energy.example", memoryKey:"path.module.energy.memory", types:["normal","electric","ice"], demo:pathImpactSpec("ice",["dragon"],[.5,1,2]), questions:[pathImpactSpec("normal",["ghost"]),pathImpactSpec("electric",["water"]),pathImpactSpec("electric",["ground"]),pathImpactSpec("ice",["dragon"]),pathImpactSpec("fire",["ice"])], prerequisites:["basics-factors"] },
      { id:"types-earth", stage:"types", number:"05", icon:"◆", titleKey:"path.module.earth.title", subtitleKey:"path.module.earth.subtitle", introKey:"path.module.earth.intro", exampleKey:"path.module.earth.example", memoryKey:"path.module.earth.memory", types:["fighting","poison","ground"], demo:pathImpactSpec("ground",["electric"],[0,.5,1,2]), questions:[pathImpactSpec("fighting",["normal"]),pathImpactSpec("poison",["grass"]),pathImpactSpec("ground",["electric"]),pathImpactSpec("fighting",["ghost"]),pathImpactSpec("ground",["flying"])], prerequisites:["basics-factors"] },
      { id:"types-mind", stage:"types", number:"06", icon:"◎", titleKey:"path.module.mind.title", subtitleKey:"path.module.mind.subtitle", introKey:"path.module.mind.intro", exampleKey:"path.module.mind.example", memoryKey:"path.module.mind.memory", types:["flying","psychic","ghost"], demo:pathImpactSpec("psychic",["fighting"],[0,.5,1,2]), questions:[pathImpactSpec("flying",["fighting"]),pathImpactSpec("psychic",["fighting"]),pathImpactSpec("ghost",["psychic"]),pathImpactSpec("psychic",["dark"]),pathImpactSpec("normal",["ghost"])], prerequisites:["basics-factors"] },
      { id:"types-material", stage:"types", number:"07", icon:"⬡", titleKey:"path.module.material.title", subtitleKey:"path.module.material.subtitle", introKey:"path.module.material.intro", exampleKey:"path.module.material.example", memoryKey:"path.module.material.memory", types:["bug","rock","steel"], demo:pathImpactSpec("steel",["fairy"],[.5,1,2]), questions:[pathImpactSpec("bug",["grass"]),pathImpactSpec("rock",["flying"]),pathImpactSpec("steel",["fairy"]),pathImpactSpec("fire",["steel"]),pathImpactSpec("poison",["steel"])], prerequisites:["basics-factors"] },
      { id:"types-myth", stage:"types", number:"08", icon:"✦", titleKey:"path.module.myth.title", subtitleKey:"path.module.myth.subtitle", introKey:"path.module.myth.intro", exampleKey:"path.module.myth.example", memoryKey:"path.module.myth.memory", types:["dragon","dark","fairy"], demo:pathImpactSpec("fairy",["dragon"],[0,.5,1,2]), questions:[pathImpactSpec("dragon",["dragon"]),pathImpactSpec("dragon",["fairy"]),pathImpactSpec("dark",["psychic"]),pathImpactSpec("fairy",["dragon"]),pathImpactSpec("fighting",["dark"])], prerequisites:["basics-factors"] },
      { id:"dual-combine", stage:"dual", number:"09", icon:"×", titleKey:"path.module.dualCombine.title", subtitleKey:"path.module.dualCombine.subtitle", introKey:"path.module.dualCombine.intro", exampleKey:"path.module.dualCombine.example", memoryKey:"path.module.dualCombine.memory", types:["water","rock","ground","flying"], demo:pathImpactSpec("water",["rock","ground"]), questions:[pathImpactSpec("water",["rock","ground"]),pathImpactSpec("ice",["dragon","flying"]),pathImpactSpec("grass",["fire","flying"]),pathImpactSpec("fire",["water","dragon"]),pathImpactSpec("normal",["rock","steel"])], prerequisites:allTypeModules },
      { id:"dual-neutralize", stage:"dual", number:"10", icon:"=", titleKey:"path.module.dualNeutral.title", subtitleKey:"path.module.dualNeutral.subtitle", introKey:"path.module.dualNeutral.intro", exampleKey:"path.module.dualNeutral.example", memoryKey:"path.module.dualNeutral.memory", types:["fire","grass","water","electric"], demo:pathImpactSpec("fire",["grass","water"]), questions:[pathImpactSpec("fire",["grass","water"]),pathImpactSpec("electric",["water","grass"]),pathImpactSpec("ice",["ground","water"]),pathImpactSpec("fighting",["dark","fairy"]),pathImpactSpec("bug",["psychic","fighting"])], prerequisites:["dual-combine"] },
      { id:"dual-immunity", stage:"dual", number:"11", icon:"0", titleKey:"path.module.dualImmunity.title", subtitleKey:"path.module.dualImmunity.subtitle", introKey:"path.module.dualImmunity.intro", exampleKey:"path.module.dualImmunity.example", memoryKey:"path.module.dualImmunity.memory", types:["electric","ground","flying","ghost"], demo:pathImpactSpec("electric",["ground","flying"]), questions:[pathImpactSpec("electric",["ground","flying"]),pathImpactSpec("ground",["flying","steel"]),pathImpactSpec("normal",["ghost","fairy"]),pathImpactSpec("fighting",["ghost","dark"]),pathImpactSpec("dragon",["fairy","dragon"])], prerequisites:["dual-neutralize"] },
      { id:"dual-mastery", stage:"dual", number:"12", icon:"◇", titleKey:"path.module.dualMastery.title", subtitleKey:"path.module.dualMastery.subtitle", introKey:"path.module.dualMastery.intro", exampleKey:"path.module.dualMastery.example", memoryKey:"path.module.dualMastery.memory", types:["fire","electric","ground","fighting"], demo:pathImpactSpec("ground",["fire","steel"]), questions:[pathImpactSpec("ground",["fire","steel"]),pathImpactSpec("fire",["water","dragon"]),pathImpactSpec("fire",["grass","water"]),pathImpactSpec("electric",["water","flying"]),pathImpactSpec("fighting",["ghost","dark"])], prerequisites:["dual-immunity"] },
      { id:"pokemon-single", stage:"pokemon", number:"13", icon:"◉", titleKey:"path.module.pokemonSingle.title", subtitleKey:"path.module.pokemonSingle.subtitle", introKey:"path.module.pokemonSingle.intro", exampleKey:"path.module.pokemonSingle.example", memoryKey:"path.module.pokemonSingle.memory", types:["water","electric","fire","psychic","normal"], demo:pathPokemonSpec(25), questions:[pathPokemonSpec(9),pathPokemonSpec(25),pathPokemonSpec(59),pathPokemonSpec(65),pathPokemonSpec(143)], prerequisites:["dual-mastery"] },
      { id:"pokemon-dual", stage:"pokemon", number:"14", icon:"◉+", titleKey:"path.module.pokemonDual.title", subtitleKey:"path.module.pokemonDual.subtitle", introKey:"path.module.pokemonDual.intro", exampleKey:"path.module.pokemonDual.example", memoryKey:"path.module.pokemonDual.memory", types:["grass","poison","fire","flying","steel"], demo:pathPokemonSpec(6), questions:[pathPokemonSpec(1),pathPokemonSpec(6),pathPokemonSpec(94),pathPokemonSpec(130),pathPokemonSpec(448)], prerequisites:["pokemon-single"] },
      { id:"pokemon-apply", stage:"pokemon", number:"15", icon:"↗", titleKey:"path.module.pokemonApply.title", subtitleKey:"path.module.pokemonApply.subtitle", introKey:"path.module.pokemonApply.intro", exampleKey:"path.module.pokemonApply.example", memoryKey:"path.module.pokemonApply.memory", types:["electric","ice","ground","fire","fighting"], demo:pathPokemonImpactSpec(130,"electric"), questions:[pathPokemonImpactSpec(130,"electric"),pathPokemonImpactSpec(149,"ice"),pathPokemonImpactSpec(6,"ground"),pathPokemonImpactSpec(229,"fire"),pathPokemonImpactSpec(248,"fighting")], prerequisites:["pokemon-dual"] },
      { id:"exam-basics", stage:"exam", number:"P1", icon:"✓", exam:true, examKind:"basics", titleKey:"path.exam.basics.title", subtitleKey:"path.exam.basics.subtitle", introKey:"path.exam.basics.intro", types:[], prerequisites:["basics-factors"], examOverall:80, examArea:60, examAreas:["direction","factors"], questions:[
        pathExamSpec(pathImpactSpec("water",["fire"]),"direction","basics-direction"),pathExamSpec(pathImpactSpec("fire",["water"]),"direction","basics-direction"),pathExamSpec(pathImpactSpec("grass",["water"]),"direction","basics-direction"),pathExamSpec(pathImpactSpec("electric",["water"]),"direction","basics-direction"),pathExamSpec(pathImpactSpec("ground",["electric"]),"direction","basics-direction"),
        pathExamSpec(pathImpactSpec("normal",["ghost"]),"factors","basics-factors"),pathExamSpec(pathImpactSpec("electric",["ground"]),"factors","basics-factors"),pathExamSpec(pathImpactSpec("fire",["grass"]),"factors","basics-factors"),pathExamSpec(pathImpactSpec("water",["grass"]),"factors","basics-factors"),pathExamSpec(pathImpactSpec("normal",["water"]),"factors","basics-factors")
      ] },
      { id:"exam-types", stage:"exam", number:"P2", icon:"18", exam:true, examKind:"types", titleKey:"path.exam.types.title", subtitleKey:"path.exam.types.subtitle", introKey:"path.exam.types.intro", types:TYPES, prerequisites:allTypeModules, examOverall:80, examArea:50, examAreas:allTypeModules, questions:[
        pathExamSpec(pathImpactSpec("fire",["grass"]),"types-elements","types-elements"),pathExamSpec(pathImpactSpec("grass",["water"]),"types-elements","types-elements"),pathExamSpec(pathImpactSpec("normal",["ghost"]),"types-energy","types-energy"),pathExamSpec(pathImpactSpec("ice",["dragon"]),"types-energy","types-energy"),pathExamSpec(pathImpactSpec("fighting",["normal"]),"types-earth","types-earth"),pathExamSpec(pathImpactSpec("ground",["flying"]),"types-earth","types-earth"),pathExamSpec(pathImpactSpec("psychic",["fighting"]),"types-mind","types-mind"),pathExamSpec(pathImpactSpec("ghost",["psychic"]),"types-mind","types-mind"),pathExamSpec(pathImpactSpec("rock",["flying"]),"types-material","types-material"),pathExamSpec(pathImpactSpec("poison",["steel"]),"types-material","types-material"),pathExamSpec(pathImpactSpec("dragon",["fairy"]),"types-myth","types-myth"),pathExamSpec(pathImpactSpec("fairy",["dragon"]),"types-myth","types-myth")
      ] },
      { id:"exam-dual", stage:"exam", number:"P3", icon:"×", exam:true, examKind:"dual", titleKey:"path.exam.dual.title", subtitleKey:"path.exam.dual.subtitle", introKey:"path.exam.dual.intro", types:["water","fire","electric","ground","fighting","ghost"], prerequisites:["dual-mastery"], examOverall:80, examArea:50, examAreas:["dual-combine","dual-neutralize","dual-immunity","dual-mastery"], questions:[
        pathExamSpec(pathImpactSpec("water",["rock","ground"]),"dual-combine","dual-combine"),pathExamSpec(pathImpactSpec("ice",["dragon","flying"]),"dual-combine","dual-combine"),pathExamSpec(pathImpactSpec("grass",["fire","flying"]),"dual-combine","dual-combine"),pathExamSpec(pathImpactSpec("fire",["grass","water"]),"dual-neutralize","dual-neutralize"),pathExamSpec(pathImpactSpec("electric",["water","grass"]),"dual-neutralize","dual-neutralize"),pathExamSpec(pathImpactSpec("electric",["ground","flying"]),"dual-immunity","dual-immunity"),pathExamSpec(pathImpactSpec("normal",["ghost","fairy"]),"dual-immunity","dual-immunity"),pathExamSpec(pathImpactSpec("ground",["fire","steel"]),"dual-mastery","dual-mastery"),pathExamSpec(pathImpactSpec("electric",["water","flying"]),"dual-mastery","dual-mastery"),pathExamSpec(pathImpactSpec("fighting",["ghost","dark"]),"dual-mastery","dual-mastery")
      ] },
      { id:"exam-pokemon", stage:"exam", number:"P4", icon:"◉", exam:true, examKind:"pokemon", titleKey:"path.exam.pokemon.title", subtitleKey:"path.exam.pokemon.subtitle", introKey:"path.exam.pokemon.intro", types:["water","electric","fire","ghost","dragon"], prerequisites:["pokemon-apply"], examOverall:80, examArea:60, examAreas:["pokemon-single","pokemon-dual","pokemon-apply"], questions:[
        pathExamSpec(pathPokemonSpec(9),"pokemon-single","pokemon-single"),pathExamSpec(pathPokemonSpec(25),"pokemon-single","pokemon-single"),pathExamSpec(pathPokemonSpec(59),"pokemon-single","pokemon-single"),pathExamSpec(pathPokemonSpec(1),"pokemon-dual","pokemon-dual"),pathExamSpec(pathPokemonSpec(6),"pokemon-dual","pokemon-dual"),pathExamSpec(pathPokemonSpec(94),"pokemon-dual","pokemon-dual"),pathExamSpec(pathPokemonImpactSpec(130,"electric"),"pokemon-apply","pokemon-apply"),pathExamSpec(pathPokemonImpactSpec(149,"ice"),"pokemon-apply","pokemon-apply"),pathExamSpec(pathPokemonImpactSpec(6,"ground"),"pokemon-apply","pokemon-apply"),pathExamSpec(pathPokemonImpactSpec(248,"fighting"),"pokemon-apply","pokemon-apply")
      ] },
      { id:"exam-final", stage:"exam", number:"P5", icon:"★", exam:true, examKind:"final", titleKey:"path.exam.final.title", subtitleKey:"path.exam.final.subtitle", introKey:"path.exam.final.intro", types:TYPES, prerequisites:["exam-basics","exam-types","exam-dual","exam-pokemon"], examOverall:80, examArea:70, examAreas:["basics","types","dual","pokemon"], questions:[
        pathExamSpec(pathImpactSpec("water",["fire"]),"basics","basics-direction"),pathExamSpec(pathImpactSpec("electric",["ground"]),"basics","basics-factors"),pathExamSpec(pathImpactSpec("normal",["water"]),"basics","basics-factors"),pathExamSpec(pathImpactSpec("fire",["water"]),"basics","basics-direction"),pathExamSpec(pathImpactSpec("ground",["electric"]),"basics","basics-direction"),
        pathExamSpec(pathImpactSpec("fire",["grass"]),"types","types-elements"),pathExamSpec(pathImpactSpec("ice",["dragon"]),"types","types-energy"),pathExamSpec(pathImpactSpec("ground",["flying"]),"types","types-earth"),pathExamSpec(pathImpactSpec("psychic",["fighting"]),"types","types-mind"),pathExamSpec(pathImpactSpec("fairy",["dragon"]),"types","types-myth"),
        pathExamSpec(pathImpactSpec("water",["rock","ground"]),"dual","dual-combine"),pathExamSpec(pathImpactSpec("fire",["grass","water"]),"dual","dual-neutralize"),pathExamSpec(pathImpactSpec("electric",["ground","flying"]),"dual","dual-immunity"),pathExamSpec(pathImpactSpec("ground",["fire","steel"]),"dual","dual-mastery"),pathExamSpec(pathImpactSpec("fighting",["ghost","dark"]),"dual","dual-mastery"),
        pathExamSpec(pathPokemonSpec(9),"pokemon","pokemon-single"),pathExamSpec(pathPokemonSpec(6),"pokemon","pokemon-dual"),pathExamSpec(pathPokemonSpec(94),"pokemon","pokemon-dual"),pathExamSpec(pathPokemonImpactSpec(130,"electric"),"pokemon","pokemon-apply"),pathExamSpec(pathPokemonImpactSpec(149,"ice"),"pokemon","pokemon-apply")
      ] }
    ];
  }

  return Object.freeze({ createModules });
});
